name: Deploy to EC2 using Docker ComposeAdd commentMore actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make SSH private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.HOST_PROD }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/back-end
            git pull origin master
            ./gradlew build
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOFAdd comment