name: Deploy to EC2 using Docker Compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make SSH private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2 and run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.HOST_PROD }} << 'EOF'
            set -e  # 실패 시 종료

            cd /home/${{ secrets.EC2_USER }}/back-end

            echo "Fetching latest code..."
            git fetch origin master
            git reset --hard origin/master

            echo "Building the project..."
            ./gradlew clean build

            echo "Restarting containers..."
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d

            echo "Deployment finished successfully."
          EOF
