name: CI for Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    name: Build and Test on Develop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with tests
        run: ./gradlew build --no-daemon
